dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.4.0
before_script:
  - yarn install
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails db:seed RAILS_ENV=test
script:
  - yarn run lint
